   ENUM_FUSION_RISK_PAGE      m_riskPage;
   CButton                    m_riskTabs[FUSION_RISK_COUNT];
   CPanel                     m_riskTabsSeparator;
   CPanel                     m_riskContentFrame;

   CLabel                     m_cfgRiskLotHdr;
   CLabel                     m_cfgRiskLotDesc;
   CLabel                     m_cfgRiskLotLbl;
   CEdit                      m_cfgRiskLotEdit;
   CLabel                     m_cfgRiskSlippageLbl;
   CEdit                      m_cfgRiskSlippageEdit;
   CLabel                     m_cfgRiskLotFoot1;
   CLabel                     m_cfgRiskLotFoot2;

   CLabel                     m_cfgRiskSLTPHdr;
   CLabel                     m_cfgRiskSLTPDesc;
   CLabel                     m_cfgRiskSLLbl;
   CEdit                      m_cfgRiskSLEdit;
   CLabel                     m_cfgRiskTPLbl;
   CEdit                      m_cfgRiskTPEdit;
   CLabel                     m_cfgRiskSLCompLbl;
   CButton                    m_cfgRiskSLCompBtn;
   CLabel                     m_cfgRiskTPCompLbl;
   CButton                    m_cfgRiskTPCompBtn;
   CLabel                     m_cfgRiskSLTPFoot1;
   CLabel                     m_cfgRiskSLTPFoot2;
   CLabel                     m_cfgRiskSLTPFoot3;

   CLabel                     m_cfgRiskPartialHdr;
   CLabel                     m_cfgRiskPartialDesc;
   CLabel                     m_cfgRiskTP1Hdr;
   CLabel                     m_cfgRiskTP1EnabledLbl;
   CButton                    m_cfgRiskTP1EnabledBtn;
   CLabel                     m_cfgRiskTP1PercentLbl;
   CEdit                      m_cfgRiskTP1PercentEdit;
   CLabel                     m_cfgRiskTP1DistanceLbl;
   CEdit                      m_cfgRiskTP1DistanceEdit;
   CLabel                     m_cfgRiskTP2Hdr;
   CLabel                     m_cfgRiskTP2EnabledLbl;
   CButton                    m_cfgRiskTP2EnabledBtn;
   CLabel                     m_cfgRiskTP2PercentLbl;
   CEdit                      m_cfgRiskTP2PercentEdit;
   CLabel                     m_cfgRiskTP2DistanceLbl;
   CEdit                      m_cfgRiskTP2DistanceEdit;
   CLabel                     m_cfgRiskFreeTPLbl;
   CButton                    m_cfgRiskFreeTPBtn;
   CLabel                     m_cfgRiskPartialFoot1;
   CLabel                     m_cfgRiskPartialFoot2;
   CLabel                     m_cfgRiskPartialFoot3;
   CLabel                     m_cfgRiskBreakevenHdr;
   CLabel                     m_cfgRiskBreakevenDesc;
   CLabel                     m_cfgRiskBreakevenEnabledLbl;
   CButton                    m_cfgRiskBreakevenEnabledBtn;
   CLabel                     m_cfgRiskBreakevenTriggerLbl;
   CEdit                      m_cfgRiskBreakevenTriggerEdit;
   CLabel                     m_cfgRiskBreakevenOffsetLbl;
   CEdit                      m_cfgRiskBreakevenOffsetEdit;
   CLabel                     m_cfgRiskBreakevenFoot1;
   CLabel                     m_cfgRiskBreakevenFoot2;
   CLabel                     m_cfgRiskTrailingHdr;
   CLabel                     m_cfgRiskTrailingDesc;
   CLabel                     m_cfgRiskTrailingEnabledLbl;
   CButton                    m_cfgRiskTrailingEnabledBtn;
   CLabel                     m_cfgRiskTrailingStartLbl;
   CEdit                      m_cfgRiskTrailingStartEdit;
   CLabel                     m_cfgRiskTrailingStepLbl;
   CEdit                      m_cfgRiskTrailingStepEdit;
   CLabel                     m_cfgRiskTrailingFoot1;
   CLabel                     m_cfgRiskTrailingFoot2;

#include "UIPanelRiskValidation.mqh"
#include "UIPanelRiskSync.mqh"
#include "UIPanelRiskBuild.mqh"
#include "UIPanelRiskVisibility.mqh"
#include "UIPanelRiskInputs.mqh"
